---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-dev
spec:
  encryptedData:
    app-secret: AgAMTQayx8icWc2D6L3qSl5cDTALox0D611xh2AgjEcgvp86+H732hKajTm79AiJ5zi9okJzs6GvCLQNitug1XHMNi9Qz4pG+S7o4ncGwZ/lf/AvLMJc4g4pOO1x5r2IuChYEtohweHZ+88dxlTBqk59ZGI2XmjknZTvGIS8AzL+NtOMSRfIFCw4DgtLEhHlJYoSPYFHIQ3kjPFrPyTbDvT4Avo0imKw9IqXaU6lFDpm/RcW8JC0a+8OEAVAtOS9PgXCxJd/R1glKHT9de+VCC5kxYuUAjEeiIIE272Qq+lg/UKB4Pja7pairD6ZxnLGal8+nIxm+AQSOjSItyHTdkBfEi3+Rku+QVnuhDm3/b6XIPf+I+wafkb8BLMRqFy6wv+OHFwdAEZHVFauE+v4RKhKcSY/F0gyqRTBz5xF+i4x/tUja944KKU4hPEXqZ9LN6D6gYIyh2ADTBId4trb/OiBZmJpCJZ7ciTT+SYGGGnrO7onUMYdpu4ym4RxF3exOzoLg4W+/UY7S6Wfnxbl9cukYVi0m0i70NTwkUsLSxHmFojEHd0/7666C1J4WEqtluDy+MhKuDkkm2vnTrspJwhYd1QYMJlIb9Oxigrp0FAlAAeTRfDj4RRTkpVAyZrQ05CIrbol+Ie8CgoURAOcyW0NboVKV4TanZ29NB8KtUplhlYFOsJUyiPvKgNsCuspRNW3COmEyMcdK0WJaOMn9JbHYrbT0/19xg==
  template:
    metadata:
      name: sample-secret
      namespace: sample-dev
