---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-dev
spec:
  encryptedData:
    app-secret: AgCEyamvTFnRQB4Jx9mQw5u7gx/P3kk2dRTtPDSgL4mSpeztVypSfAXaFjEmvn8R87nExGJUG/SwjDFhZn3lZPcWYnPqbu72H1bIrXvs3gMVbeQaizMSLZAbP6Ikg5SaLOXKSv9HLI6hV7cq85Ed0II8frCecGxzx/EnP5eezjAEc39sUl9HvZuad1NxfikrIlGdxRrXRWmETxjrDk/6gxMRrTM/6AZbzk+Fi+3vSiqBvOmN+wCAdnrmtGiu+vsJ4S2nM+nK0+0MPAUH3fk6wBR3ga9M4n5TgA1La6ExKxrq3p6HUD6YFt0jQNmWCYqOqPCdwosnR7c/R8eAREEiXEDx2mU66e+TUyuYyj4g9tub6LTBd1MgNfC7LbahzaUOekzKo8CTZIr1L1ITpxBJPkRQh52z+MqFWQtbrm3ryWH2JDYwOzQowV760mXr63vpENFt0rwcxUk7YBcxIan8szPm4bEYK4DYfCNf0vXuyfbkPUQ7sClabbCU8A+SBiTVBLHryuL1r+CLvOabRbz26p5p7vRyD0rZyavdcS2652ODdvUEPox1xAkrTYNwVNJK1rtNvOLgB+AXh8EkRWmRB4AtRKH6F8HFpFFBxyg/w6wIBx4aASfKRoaZYWxcoRixVPGqmuemypd7+pD9rKuuoEYgVOOLMeqLf7ZMWoeIBi5G2daGQxQ8Hj9je/on/I5gAodFM1IV5v3plXokf/wOyIA/B6tBBSHC0Q==
  template:
    metadata:
      name: sample-secret
      namespace: sample-dev
