---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-staging
spec:
  encryptedData:
    app-secret: AgCd0bTe6/ScYZU9W/mDBgXxfZXJsHWqSCtlPIk1E4fTEEeB7PTE3ys7DJ6m3GnXtkRhvcc19IhK2+ySNvwVOLfuB30Qw9Xwy/N6a1PMlRNBFxM+LETQFXQsNrzyDztPk9DdCou9uJI8AEBXIiiNYzAhfEMWcG3PDTrL9rrqr146FQfWupA8TcjB2iAPanxPUOjqjVVRqvQIP5c6XFXaXVLm37vKBzqZ48qRyweMmCOuKh39hd6Bgu39EO4WvZsPwsWjqBJu0aJk7SZKRmGDkLXbPKxhKmLgGa9j4L61hXvfnWaQ87uF8EzBJXfjeLEsHc4MDJQpUQjPnTNJj1dD14zWoRFt4LXHnatGH9uX/XJlAeJlIoTvpH8b0sN6Sp71RxCAufCymlnJnAG+JNkW+T1409Y/4csXEUmRnhIyhujuTMC1rVcYDy3K7XsyitXa15XSvTM4KW0vXhfI2GAK6C3isfmCGQIqBUkpt4RGwesmzBW/bz7gO/ovQYWbE3PEuh9o7gxSWeNDzPnjEckKdZ1lElzYAd7hKhMmmU0lv7Zq5KX05acp90ucbH1bPOd9px11TdKzfvlhKOUJ8MOM50QvCjwHDHcKrAgUQRvR9nTSKU8lrcBA50TYitknomOp35Udhx7rOTe4o+v3BN+hnbV7lvBU30/Y53SeXmrLbSxmmv6bhlw5zYZMj8+6uG62Or1ujGu38VaQHnmqmA7r0r4wVA7s4lQgqxUQF9w=
  template:
    metadata:
      name: sample-secret
      namespace: sample-staging
