---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-staging
spec:
  encryptedData:
    app-secret: AgCnyQID+9RPZ8n60m64VoiaJArLmXJbyrMyF0eOGJrdlmonJR7xKXpQoTRROmkzsIu/5Qih6wiJdArgju1mZhaUfFR1/xDwMUkHJKR74LcNaBNzG5GrpCbeIqpRYaZkxgntYxrVR1lFQtCeE1/wC7/eoeRm9+I8q1Jz6zMEyqfAHNQKTahaQmKP0YEN5t8kpfcCg0Q7tHr3dtWhoFODVAw24ArYwqTQY5OKT9iSavqNVOddl2kx6IovkNzttEuBnoCDwZ1Bl5kZ4rvA91XzIWx1jULMqL6jqYpwxyqXfOc+juE0Jo9vfxrOfkcenqn5+JpDHsHHo3p8V/++bqJccwjLQO/4YOEPqv5d+C8aKra/2obKP5FxwmKrYb4wemPFWNGLgSBsccmUBSuiKVY9YuOjxvuaoyNEUdFrba9+1rXXuvyomZh9pCBztuk6xsyqmonwpTicG6ioH1w0TAfX5lIyMQKBBM0pd/4dLPeHQqp67o1vZ+u/5xWDn6NYoVkJCWsXwvVnfBEyuh49uyGOOTgLZb7pITG1rHhJ/7HMy38pzHCPftFanBJtFxG29Mpu6ZtKnBxmSFDsd6+as+FChdoqgHcLMQVSgDIV23KZEkcBhl/0SqnTZeVfyj+6WY1E5+zMu+iWSZ4cbZQOqLQ9crxC+KikAtJm+9UsHZ3hddAGsq5KihSTQTc/AxyiLaysDuSPgx823Az44ar+VFz3zhnMltdV5rzephtm3+A=
  template:
    metadata:
      name: sample-secret
      namespace: sample-staging
