---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-pr-1
spec:
  encryptedData:
    app-secret: AgCUXaxTzURz5zYhV7fIxXfUCehoRjLdZ0cmdqyUDwn599ux3tfgviJOHXgO202lrPnqnGiCnFi38Tydy4Qf5KSHLLzJGovptqI6oGHN9SQoQ5TE6WJNr0mDKk3lsTVDv9p5XmP7699FhqaHkLTge4dBAzDSnpF6ZjZqtgybvEv4lnKvQ531HbB8CUV4of7+3Z+fSpg/ciCkSWaSRrS5Ajk8wLgYitSjmCXJarxp3kooMNlJJbmL3fabCvJ/EvT00Xni/rUA7e9i5Q5JKzlegfQv7mfs2aZSfbdrIOvhvZNL+7oXUBz/cbZobMJ/Q82mxDREoArSImRk8HjzQjD+bkLoS+yZAa4Sf2OtIqRRIPV7Sh56w+9+Vb2qAWJeCfCCCg3v4CilXKUe75znfhLuiL0Ko47vc8lBNOVb/y0b8jkeHbw7UahV+BjcBiOlnpy1+DhZ8C8RAyg40dFWDP3HYBZd/cMqYWDduvIYsBSoXdLzZp31BhD9DueCy8uLP2A2cOgiHyFC7Pg5WbaquOljbNSjMI1iBLItrMDxETVMT3XWbvjBiOLZBurMklFW6laPOduDNylg7B0iMI9Qi3Y52FwN0zH1gDoYvy6PNIkU4xGYPMdgc92wb7eGxcU2U5YUhLN8B6LzIVfiWw3AO8crSG0ZwbQMNzHHoHAlXvWzj/zGAnN6DfUKbxCnZYbKR4aRjJwSCCqtpFXimWbiItKG1Hns2CiGpuscZvarBU0=
  template:
    metadata:
      name: sample-secret
      namespace: sample-pr-1
