---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-pr-1
spec:
  encryptedData:
    app-secret: AgA27sSCzXfN++N5G1bRXvzC/BF6VnXsLQ3x/+Pyn3SB4V3ClBQuG+ehSCMQGM6gEswerVfKFUdlzmmipkbLsAzxAI3NL4q8F+9MAw5/XpqDXg60fBeW3OQbWZRP5Irxq8pAa9VI9HggBaOP08AQSmxXAvj0qsO32djaewYe05i/RVRC1ISLDZdqUrPdL5W/WTJmgmeJF7WfqIR67CrdzZTi1PCzKRXJNEzWj6WEhKD7AwzIvS6d35dOBR9upMLds8BSH6cATY5lS0/MAir6Qpcxvrv5n85yA3m2eBjzm+60Sv23zjfJ94qJlEgaFyyinWFYjLIzS7BcQP0Vj55GluB7TceMlJmlQjVjMJwi5dHoUMaZ3tVgxciDN3/jv607Zk6LuijSqs4fvHtEuXPUr672lOiU1zie7+WZZGe6+fBd1/fbmdClzt4CTybB9v/F2u4pp6ynXkAHaAD54acHdppvMpqafGJpuGROpjf8kR2GT2vx/LRcrQT902qzeXlremPwGMT6jG5VMp/DlphED0wNfAl7mAJE4fBamU612BTIkfrBdPPA/E/WJn18j2eERzxk+WioNA0L+LWlmwEC6nKG/sOeXsIlWZHwLGWb/WnJ9LzBnvvZiFQs6MwivRuQHcySsp/ilbrZguTxpAL4FylIctVih5hP+jdIt9Sm2Pv7mgAetpDJxPDO4tbOQiUdVMU2QQYjWFneGUz2tnuk3J8jbPVg6NhVkM4R2hs=
  template:
    metadata:
      name: sample-secret
      namespace: sample-pr-1
