---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-prod
spec:
  encryptedData:
    app-secret: AgAdhgoblT1HfDnuDtR+KI4ZwpXK8a3H328dzC73kP8P1QrDUHdubZcFJNOAOy0IHH2eLHfg3QKhALFFXeKD0fUC+imVNUeAlTrSGNgz+FKAyexye40fa4JGqeBZ4YfaKrd/vrhxojPGru2HBppXMHCjpMqhgIi2gYmdb4mxRlFY7qra5T/JUhqtUzxWXD0RiDdEHOV5kC9R4tJJUCnlfLtex7wKVuX2qvfTmnb6fijIX8EqPS27wNaQ/GYT8zdmAgnzlmmnkdsB8sBUWxqt8E9AwYFCtMnhsljCMnQi0djrxKp/1LLJSuwO1aRxtchFWuecE5CULR5KEtJoMhuM7w9WEouv3fyiecXTDI5+o8MncgdkmFozrRYiTUKH/qGWxyU/zXzJoUIRQVSxwgeM6Fx1DfWEPE7NjQV/Mlypq2B/5C1NKPgp5nfIShx66YW1BU8Wv93X57Mh/SomOzb6Lk1WuddKep38yWP0Y0C4LDZRKpW9f0onYWucH3rufWpNJWkTnfYgkJmkmnamuGrN9jWHRu6Zof/tra/5sslzdidAvEMc/FdkcADiyxnDQf2XH94kz2tW/e3Tv5hteTzcqu10cFY1WZyV5x18rAdhGytG+SL+uVqEaRV09GX0coOdPHhIXWCIOj1lduJUFGJ0lbdMC2H1IMa6G/bgBCx3uy3x5aoUt6zMEVOWa1EL61vk4t3tEASS5E3IHzF3pYeCjSK2/lWsA500zXs=
  template:
    metadata:
      name: sample-secret
      namespace: sample-prod
