---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-secret
  namespace: sample-prod
spec:
  encryptedData:
    app-secret: AgCkAzlENEbP4DE62c1tCJWf4FM7wkR94OkLs9zgPnvQbPZgSdsVmQMVSw9OxRGhPssJ7DiV4ie6Xsck+c7UVUvZMH6D84NqC9JXEOFxvCs1/t/+u+6qaiCWpgVO/CNWdN7wZFKolHL9KxAzr4wpDUVOjzEx1GUomLu4mA1IKEbM/Vd1PpH2g0M7PNNZu6HGBiZRZG4+u903LoUZ/3NVPdVCHoXupOfIm4r3vN4MLEnjW+b+rf0N+fipUgdEdDus7yMEw75ods1KPnoptaF8DHgWY/o7noKI0Rrfs+b8fTanvmEe8kfscfwWvaplG/lIxErrTQ5mv5XWqvUmShrMHN8sAIKl7Vk84ijJGJjAiBDtLqGMzCAZ3LGukYE4aeKjuPRqT4fxBcF+kh0/blrAIHtG/BL4yA/HKUiakCFMw0EJE1WJY/zJXyt3KAGrbesPJ968BgLTAj2mD6NBIE1Na2PTKwthCIfIamvoSv6LR1PzK7txPxYE3s18otbV2EVDWAuFxZuRz22A3N31fas9rXPmnmSYbe2edOs8tM1w3Lyp4lWen+c2jrjcXZViiouaQWKhXL5+Re0jNmoHuscRqaJ2uOMHbRRKU0oey0JlL/qZfBu2W8Q7wXjm34NoLDngp+TWa67eHe9MJ9WfTTVrm/QGn/f3KOgGypYBZupBuAA1eVF+MB7XCTNBZRa/hcUafmh0fixNBarDTAHj+AYi9SfgMZHB2bAoAkY=
  template:
    metadata:
      name: sample-secret
      namespace: sample-prod
